language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1

install:
  - mix local.hex --force
script:
  - elixir saying_hello.exs
  - elixir counting_characters.exs
  - elixir print_quotes.exs
  - elixir anagram.exs
